#
# Title: The Advertising-Tracking List
# Version: Blue
# Homepage: https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/
# Last modified: 2026-09-06T08:29:56.495Z
#
# Rules: 1
#
address=/doubleclick.net/0.0.0.0