#
# Title: The Advertising-Tracking List
# Version: Blue
# Homepage: https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists/
# Last modified: 2026-08-09T20:26:47.021Z
#
# Rules: 2
#
address=/blue-ad.firebog-aio.tld/0.0.0.0
address=/blue-track.firebog-aio.tld/0.0.0.0